FT_DPCM_PTR=$c000
	.export _shooter_music_data
;this file for FamiTone2 library generated by text2data tool

_shooter_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env4,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cd,$c8,$c5,$c3,$c1,$00,$04
@env2:
	.byte $cc,$c9,$c6,$c4,$c3,$c3,$c4,$ca,$cd,$00,$08
@env3:
	.byte $cd,$ca,$c9,$c8,$c6,$c5,$c5,$c4,$c4,$c4,$00,$09
@env4:
	.byte $c0,$04,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $00,$9d
@ref1:
	.byte $9f
@ref2:
	.byte $9f
@ref3:
	.byte $9f
@ref4:
	.byte $80,$3a,$3a,$3a,$3a,$40,$85,$3a,$3a,$3a,$3a,$44,$85
@ref5:
	.byte $3a,$3a,$3a,$3a,$40,$85,$49,$47,$45,$40,$81
@ref6:
	.byte $3a,$3a,$3a,$3a,$40,$85,$3a,$3a,$3a,$3a,$44,$85
@ref7:
	.byte $53,$4f,$49,$45,$41,$3b,$37,$3a,$81
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$0b
	.word @ref5
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$09
	.word @ref7
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$0b
	.word @ref5
	.byte $ff,$0c
	.word @ref6
@ref15:
	.byte $3b,$3a,$00,$85,$3b,$3b,$00,$87
@ref16:
	.byte $84,$3a,$44,$48,$44,$3a,$44,$48,$44,$3a,$44,$48,$44,$3a,$4e,$48
	.byte $44
@ref17:
	.byte $40,$44,$48,$44,$40,$44,$48,$44,$40,$44,$48,$44,$40,$4e,$48,$44
@ref18:
	.byte $3a,$44,$48,$44,$3a,$44,$48,$44,$3a,$44,$48,$44,$3a,$4e,$48,$44
	.byte $ff,$10
	.word @ref17
	.byte $ff,$10
	.word @ref18
	.byte $ff,$10
	.word @ref17
	.byte $ff,$10
	.word @ref18
@ref23:
	.byte $40,$44,$48,$44,$40,$44,$48,$44,$40,$44,$48,$44,$4e,$52,$86,$58
	.byte $81
@ref24:
	.byte $84,$52,$5c,$60,$5c,$52,$5c,$60,$5c,$52,$5c,$60,$5c,$52,$66,$60
	.byte $5c
@ref25:
	.byte $58,$5c,$60,$5c,$58,$5c,$60,$5c,$58,$5c,$60,$5c,$58,$66,$60,$5c
@ref26:
	.byte $52,$5c,$60,$5c,$52,$5c,$60,$5c,$52,$5c,$60,$5c,$52,$66,$60,$5c
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref26
	.byte $ff,$10
	.word @ref25
@ref30:
	.byte $86,$53,$52,$89,$00,$8d
@ref31:
	.byte $53,$52,$89,$00,$8d
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref32:
	.byte $82,$0a,$0a,$0a,$0a,$10,$0a,$0a,$0a,$0a,$06,$0a,$0a,$0a,$10,$14
	.byte $18
@ref33:
	.byte $0a,$0a,$0a,$0a,$10,$0a,$0a,$0a,$0a,$06,$0a,$0a,$0a,$10,$10,$10
@ref34:
	.byte $0a,$0a,$0a,$0a,$10,$0a,$0a,$0a,$0a,$06,$0a,$0a,$0a,$10,$14,$18
@ref35:
	.byte $80,$22,$1e,$18,$14,$0a,$06,$0a,$06,$06,$06,$82,$0a,$14,$18,$14
	.byte $14,$14
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref33
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref35
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref33
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref35
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref33
	.byte $ff,$10
	.word @ref34
@ref47:
	.byte $0b,$0a,$00,$85,$0b,$0b,$00,$87
@ref48:
	.byte $86,$0b,$11,$15,$19,$0b,$11,$15,$18,$81
@ref49:
	.byte $0b,$11,$15,$19,$0b,$11,$15,$18,$81
@ref50:
	.byte $0b,$11,$15,$1b,$0b,$11,$15,$1a,$81
	.byte $ff,$09
	.word @ref50
	.byte $ff,$09
	.word @ref49
	.byte $ff,$09
	.word @ref49
	.byte $ff,$09
	.word @ref50
	.byte $ff,$09
	.word @ref50
	.byte $ff,$09
	.word @ref49
	.byte $ff,$09
	.word @ref49
	.byte $ff,$09
	.word @ref50
	.byte $ff,$09
	.word @ref50
	.byte $ff,$09
	.word @ref49
	.byte $ff,$09
	.word @ref49
@ref62:
	.byte $0b,$0a,$89,$00,$8d
	.byte $ff,$05
	.word @ref62
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref64:
	.byte $9f
@ref65:
	.byte $9f
@ref66:
	.byte $9f
@ref67:
	.byte $9f
@ref68:
	.byte $9f
@ref69:
	.byte $9f
@ref70:
	.byte $9f
@ref71:
	.byte $9f
@ref72:
	.byte $9f
@ref73:
	.byte $9f
@ref74:
	.byte $9f
@ref75:
	.byte $9f
@ref76:
	.byte $9f
@ref77:
	.byte $9f
@ref78:
	.byte $9f
@ref79:
	.byte $9f
@ref80:
	.byte $9f
@ref81:
	.byte $9f
@ref82:
	.byte $9f
@ref83:
	.byte $9f
@ref84:
	.byte $9f
@ref85:
	.byte $9f
@ref86:
	.byte $9f
@ref87:
	.byte $9f
@ref88:
	.byte $9f
@ref89:
	.byte $9f
@ref90:
	.byte $9f
@ref91:
	.byte $9f
@ref92:
	.byte $9f
@ref93:
	.byte $9f
@ref94:
	.byte $9f
@ref95:
	.byte $9f
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref96:
	.byte $82,$0a,$0a,$0b,$1d,$0b,$0b,$0b,$1d,$0a,$81
@ref97:
	.byte $0a,$0a,$0b,$1d,$0b,$0b,$0b,$1d,$0a,$81
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
@ref108:
	.byte $80,$0a,$0a,$0b,$1d,$0b,$0b,$0b,$1d,$0a,$81
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
@ref111:
	.byte $0b,$0a,$00,$85,$82,$0b,$0b,$00,$87
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref97
	.byte $ff,$0a
	.word @ref108
@ref125:
	.byte $0a,$0a,$0b,$1d,$0b,$0b,$0b,$0b,$1c,$81
	.byte $ff,$05
	.word @ref62
	.byte $ff,$05
	.word @ref62
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref128:
	.byte $9f
@ref129:
	.byte $9f
@ref130:
	.byte $9f
@ref131:
	.byte $9f
@ref132:
	.byte $9f
@ref133:
	.byte $9f
@ref134:
	.byte $9f
@ref135:
	.byte $9f
@ref136:
	.byte $9f
@ref137:
	.byte $9f
@ref138:
	.byte $9f
@ref139:
	.byte $9f
@ref140:
	.byte $9f
@ref141:
	.byte $9f
@ref142:
	.byte $9f
@ref143:
	.byte $9f
@ref144:
	.byte $9f
@ref145:
	.byte $9f
@ref146:
	.byte $9f
@ref147:
	.byte $9f
@ref148:
	.byte $9f
@ref149:
	.byte $9f
@ref150:
	.byte $9f
@ref151:
	.byte $9f
@ref152:
	.byte $9f
@ref153:
	.byte $9f
@ref154:
	.byte $9f
@ref155:
	.byte $9f
@ref156:
	.byte $9f
@ref157:
	.byte $9f
@ref158:
	.byte $9f
@ref159:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
